### ISSUE TITLE
Admin login access for users

### ISSUE THREAD

**Issue by JsutterIntulse** [intulse/intulse-beta#18]
**Is your feature request related to a problem? Please describe.**
If a user is unable to log in to the dashboard, admins are unable to verify the E-mail address needed to login. 

**Describe the solution you'd like**
A feature so admins of the dashboard on our end can change/set the email address used to log into the dashboard for other users. Suggest adding it to the Admin-Extensions screen in the dashboard.

**Additional context**
This would be particularly helpful if there is an error in the email address or a similar issue that just needs a quick fix

**Comment by darrenhollick** [comment]
This is now accomplishable in the new Account Center
